micronaut:
  application:
    name: edh-ranking
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    url: jdbc:postgresql://34.118.35.246:5432/postgres
    username: postgres
    password: mtg
flyway:
  datasources:
    default:
      enabled: true
