micronaut:
  application:
    name: edh-ranking
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
flyway:
  datasources:
    default:
      enabled: true
  server:
    port: ${PORT:8080}
    cors:
      enabled: true