micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
      single-header: true
  application:
    name: edh-ranking
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
flyway:
  datasources:
    default:
      enabled: true
  server:
    port: ${PORT}
    cors:
      enabled: true